# Generated by Django 5.1.4 on 2026-02-08 18:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_productimage_image_productimage_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNotification',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_notifications', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('email', 'product')},
            },
        ),
    ]
