# Generated by Django 5.1.4 on 2026-03-18 14:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('discount_percentage', models.IntegerField(default=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('banner_color', models.CharField(default='#FF3F6C', max_length=20)),
                ('products', models.ManyToManyField(blank=True, related_name='flash_sales', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
    ]
